---
title: "Untitled"
author: "Dr. Williams"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I need these packages:
```{r}
library(tidyverse)
library(pwt10)
library(countrycode)
library(coolorrr)
set_palette()
```

Here's the data I want to use:
```{r}
pwt10.0 %>%
  filter(year == max(year)) -> Data
```

I want to make a world map to show the distribution of GDP/capita.
```{r}
worldmap <- map_data("world")
worldmap$country_id <- countrycode(worldmap$region,
                                   "country.name",
                                   "cown")
Data$country_id <- countrycode(Data$country,
                               "country.name",
                               "cown")
Data$gdpcat <- cut(Data$rgdpna / Data$pop,
                   breaks = quantile(Data$rgdpna / Data$pop,
                                     c(0, 0.2, 0.4, 0.6, 0.8, 1)),
                   include.lowest = T,
                   ordered_result = T,
                   labels = c("1st",
                              "2nd",
                              "3rd",
                              "4th",
                              "5th"))
worlddata <- left_join(worldmap, Data, by = "country_id")


ggplot(worlddata) +
  aes(x = long,
      y = lat,
      group = group,
      fill = as.numeric(gdpcat)) +
  geom_polygon(size = 0.1,
               color = "black") +
  ggpal(type = "sequential",
        aes = "fill",
        breaks = as.numeric(unique(Data$gdpcat)),
        labels = unique(Data$gdpcat)) +
  theme_void() +
  labs(fill = "Quintiles",
       title = "GDP per capita, 2019") +
  theme(legend.position = "bottom")
```


```{r}
worldmap %>%
  mutate(
    dr = case_when(
      region == "USA" ~ "Donor",
      region == "Pakistan" ~ "Recipient",
      TRUE ~ NA
    )
  ) %>%
  ggplot() +
  aes(x = long,
      y = lat,
      group = group,
      fill = dr) +
  geom_polygon(color = "black",
                size = 0.1) +
  ggpal(aes = "fill",
        na.translate = F) +
  theme_void() +
  labs(fill = "Countries in sample: ",
       title = "Limited Sample") +
  theme(legend.position = "bottom")
  
```

```{r}
list_of_donors <- c("Finland",
                    "Australia",
                    "Austria",
                    "Belgium",
                    "Canada",
                    "Czech Republic",
                    "Germany",
                    "Denmark",
                    "Spain",
                    "France",
                    "UK",
                    "Greece",
                    "Hungary",
                    "Ireland",
                    "Iceland",
                    "Italy",
                    "Japan",
                    "South Korea",
                    "Luxembourg",
                    "Netherlands",
                    "Norway",
                    "New Zealand",
                    "Portugal",
                    "Slovakia",
                    "Slovenia",
                    "Sweden",
                    "USA",
                    "Switzerland")
`%nin%` <- Negate(`%in%`)
worldmap %>%
  mutate(
    dr = case_when(
      region %in% list_of_donors ~ "Donor",
      region %nin% c("Antarctica", "Greenland") ~ "Recipient",
      TRUE ~ NA
    )
  ) %>%
  ggplot() +
  aes(x = long,
      y = lat,
      group = group,
      fill = dr) +
  geom_polygon(color = "black",
                size = 0.1) +
  ggpal(aes = "fill",
        na.translate = F) +
  theme_void() +
  labs(fill = "Countries in sample: ",
       title = "More Complete Sample") +
  theme(legend.position = "bottom")
```

```{r}
worldmap %>%
  filter(region == "USA",
         subregion %nin% c("Hawaii", "Alaska")) %>%
  ggplot() +
  aes(x = long,
      y = lat,
      group = group) +
  geom_polygon(fill = "darkblue") +
  theme_void() +
  coord_map(
    projection = "albers",
    lat0 = 39,
    lat1 = 41
  )
```

```{r}
worldmap %>%
  filter(region == "Pakistan") %>%
  ggplot() +
  aes(x = long,
      y = lat,
      group = group) +
  geom_polygon(fill = "darkred") +
  theme_void() +
  coord_map(
    projection = "albers",
    lat0 = 39,
    lat1 = 41
  )
```

```{r}
worldmap %>%
  filter(region == "Albania") %>%
  ggplot() +
  aes(x = long,
      y = lat,
      group = group) +
  geom_polygon(fill = "forestgreen") +
  theme_void() +
  coord_map(
    projection = "albers",
    lat0 = 39,
    lat1 = 41
  )
```

```{r}
set_theme()
ggplot() +
  aes(x = 86,
      y = "1") +
  geom_col(size = 0.5) +
  scale_y_discrete(
    breaks = NULL
  ) +
  labs(x = "Count",
       y = NULL,
       title = "New Alliances, 2005-2014") -> p
p + geom_text(aes(label = "86 new alliances",
                  x = 86/2),
              color = "white",
              size = 5)
```

```{r}
p + geom_col(aes(x = c(57, 29),
                 y = "1",
                 fill = c("more", "less"))) +
  ggpal(aes = "fill") +
  theme(legend.position = "none") +
  geom_text(aes(x = c(57/2, 57 + 29/2),
                label = c("Increase in Aid = 57",
                          "Cut to Aid = 29")),
            color = "white",
            size = 5,
            fontface = "bold")
```

```{r}
tibble(
  model = c("D-in-D", "D-in-D", "Lagged-DV", "Lagged-DV"),
  term  = c("Nonaggression", "Defense", "Nonaggression", "Defense"),
  est   = c(0.48, -0.38, 0.33, -0.34),
  sdter = c(0.11, 0.15, 0.08, 0.14),
  lower = est - 1.96 * sdter,
  upper = est + 1.96 * sdter
) %>%
  mutate(
    across(c(est, lower, upper),
           ~ 100 * (exp(.x) - 1))
  ) -> to_plot
```

```{r}
set_palette(
  qualitative = c("darkblue", "indianred"),
  from_coolors = F
)
library(geomtextpath)
p0 <- ggplot(to_plot) +
  aes(x = est,
      y = model,
      xmin = lower,
      xmax = upper) +
  labs(x = "(%) Difference made by the alliance",
       y = NULL,
       title = "Results from the Analysis")
p0
p0 +
  geom_textvline(
    xintercept = 0,
    linetype = 2,
    label = "No Difference"
  ) +
  geom_errorbar(alpha = 0) -> p1
p1
p1 +
  geom_pointrange(
    data = to_plot %>% filter(model == "D-in-D"),
    #aes(color = term),
    show.legend = F
  ) -> p2
p2
p2 +
  geom_text(
    data = to_plot %>% filter(model == "D-in-D", term == "Nonaggression"),
    label = "95% CI",
    hjust = -1,
    vjust = -1
  ) -> p3
p3
p2 +
  geom_pointrange(
    data = to_plot %>% filter(model == "D-in-D"),
    aes(color = term),
    show.legend = F
  ) +
  ggpal() +
  geom_text(
    data = to_plot %>% filter(model == "D-in-D"),
    aes(label = term),
    vjust = 2
  ) -> p4
p4
p4 +
  geom_pointrange(
    #data = to_plot %>% filter(model == "D-in-D"),
    aes(color = term),
    show.legend = F
  ) +
  ggpal() +
  geom_text(
    #data = to_plot %>% filter(model == "D-in-D"),
    aes(label = term),
    vjust = 2
  ) 
```

