---
title: "Evals: Fall 2022"
author: "Miles D. Williams"
date: '2023-06-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = F,
                      warning = F)
library(tidyverse)
library(kableExtra)
library(socsci)
library(googlesheets4)
gs4_deauth()
```

Get the student evals:

```{r}
ids <- c(
  "1hizYlLWrF55Q9AJbUf8uLPOZL9i18tfi",
  "1QQQsyHIiPeoa_904As4GJ6EbOV1pVBUL",
  "1GOx8ZxWm-RLHGQjPYIg3ba9IIPgnNo5e",
  "1Y-ImrZd-_4ADsGMTSLZImhj4u-qHW-TP"
)
urls <- sprintf("https://docs.google.com/uc?id=%s&export=download", ids)
names(urls) <- c(
  "DPR101",
  "DPR190_01",
  "DPR190_02",
  "POSC101"
)
urls |>
  map(
    ~ read.csv(.x)
  ) -> Data
Data$DPR101$course <- names(urls)[1]
Data$DPR190_01$course <- names(urls)[2]
Data$DPR190_02$course <- names(urls)[3]
Data$POSC101$course <- names(urls)[1]
Data <- bind_rows(Data)
```


Okay, let's summarize by course.

```{r}
Data |>
  select(course, where(is.numeric), -Year) |>
  pivot_longer(-course) |>
  group_by(course, name) |>
  mean_ci(value >= 4) |>
  mutate(mean = paste0(round(100 * mean, 2), "%")) |>
  select(1:3) |>
  pivot_wider(names_from = course,
              values_from = mean) |>
  mutate(
    name = str_replace(name, "\\.", " ")
  ) |>
  rename(
    Metric = name
  ) -> out_f22
write_csv(
  out_f22,
  here::here("Misc",
             "Evals Analysis",
             "course_evals_f22.csv")
)  
```

