---
title: "Analysis Challenge 2"
output: pdf_document
fontfamily: cochineal
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


For this analysis challenge, your objective is to forecast President Biden's popular vote in 2024. You'll first put together a predictive model using the dataset introduced below. You'll then simulate some predictions for 2024. 

For the first part of this assignment, in addition to writing the code necessary to make your predictive model, I want you to briefly justify why you picked the predictor variables that you did. You can do this in a paragraph before the code chunk where you make your predictive model.

For the second part, I want you to use your predictive model to simulate a few different scenarios for 2024:

1. Based on the variables you included in the model, what values would give you a best-case scenario for Biden?
2. Similarly, what values would give a worst-case scenario?
3. Finally, go online and see if you can identify reasonable values for the predictor variables you've included in your model to give you a most-likely scenario for Biden.

After you've done the above, conclude by speculating about Biden's chances in the upcoming election. Based on your model, do you think he's likely to win?


## The data

You can access and read in the data using the following url:

https://raw.githubusercontent.com/milesdwilliams15/Teaching/main/DPR%20201/Data/prez_data.csv

The each row in the dataset is a particular presidential election year running from 1948 to 2020. For each election, it contains information for the following variables:

- `year`: The election year
- `inc_party`: Tells you whether the incumbent party is the Democrats or Republicans
- `inc_running`: A binary indicator for whether the incumbent president is running for office again
- `dem`: The Democratic candidate's approval rating
- `rep`: The Republican candidate's approval rating
- `inc_approval`: The incumbent party candidate's net approval relative to their opponent
- `third_party`: A binary indicator for whether a third party candidate is running
- `inc_vote`: The share of the popular vote won by the incumbent party candidate
- `gdp`: Gross domestic product (GDP) in the second quarter of the election year
- `gdp_growth`: Change in GDP from the first to the second quarter of the election year
- `gdp_pct_growth`: The percent change in GDP from the first to the second quarter of the election year