---
title: "Analysis Challenge 4"
subtitle: "Due Monday, Feb. 4"
format: pdf
editor: visual
---

## 

We've been discussing the problem of *p-hacking*, which is the process of changing aspects of your data analysis such as your measures, your sample, and/or your statistical model until you can turn a statistically insignificant result into a significant one. For this analysis challenge I want you to use some data that Bueno de Mesquita and Fowler made available on their book's website. This data gives us an opportunity to ask an interesting question: did prior exposure to Donald Trump in pop-culture influence political behavior in 2016? To capture prior exposure, the survey asked responds two questions: (1) whether they watched *The Apprentice*, a TV show starring Trump, and (2) whether they watched *Home Alone 2*, a movie with a Trump cameo.

Using the data:

1.  See if you can find at least three statistically significant relationships between prior exposure to Trump and political behavior. You're free to look at how individuals voted in 2016 or whether they even voted at all in 2016. You can test whether watching either show or both shows influences one of these outcomes. You can also control for as many or as few additional factors that you want in a regression model. You can also pick and choose what kind of standard errors you'd like to use—classical or robust.
2.  Once you find three statistically significant relationships, interpret them substantively. Have we learned anything new about political behavior in the electorate from your analysis? Write a paragraph summarizing your thoughts.

Once your done, submit your work as a rendered Quarto document with your code visible and your interpretation of the results.

\clearpage

## Data

The file "VoterSurveyData2016.csv" on my GitHub contains data from a survey of 1,000 eligible U.S. voters shortly after the 2016 presidential election. You can read in the data to R from the following url: <https://raw.githubusercontent.com/milesdwilliams15/Teaching/main/DPR%20201/Data/VoterSurveyData2016.csv>

Each row corresponds to a unique respondent, and each column corresponds to a survey question or characteristic of the respondent.

Below is a description of variables.

-   id: a unique identification number assigned to each respondent

-   voted16: 1 if the respondent was verified (by their state) as having voted in the 2016 presidential election, 0 otherwise

-   trump16: 1 if the respondent reported voting for the Republican candidate, Donald Trump, in 2016, 0 otherwise

-   clinton16: 1 if the respondent reported voting for the Democratic candidate, Hillary Clinton, in 2016, 0 otherwise

-   voted12: 1 if the respondent reports that they voted in the 2012 presidential election, 0 otherwise

-   obama12: 1 if the respondent reported voting for the Democratic candidate, Barack Obama, in 2012, 0 otherwise

-   romney12: 1 if the respondent reported voting for the Republican candidate, Mitt Romney, in 2012, 0 otherwise

-   democrat: 1 if the repondent identifies as a Democrat, 0 otherwise

-   republican: 1 if the respondent identifies as a Republican, 0 otherwise

-   liberal: 1 if the respondent identifies as liberal, 0 otherwise

-   conservative: 1 if the respondent identifies as conservative, 0 otherwise

-   age: respondent's age at the time of the November 2016 election

-   female: 1 if the respondent identifies as female, 0 otherwise

-   white: 1 if the respondent identifies as white, 0 otherwise

-   black: 1 if the respondent identifies as black, 0 otherwise

-   hispanic: 1 if the respondent identifies as hispanic, 0 otherwise

-   asian: 1 if the respondent identifies as asian, 0 otherwise

-   income100: 1 if the respondent reports that their family income exceeds \$100,000 per year, 0 otherwise

-   church: 1 if the respondent reports attending church at least once per week, 0 otherwise

-   south: 1 if the respondent is from a southern U.S. state, 0 otherwise

-   apprentice: 1 if the respondent reports having watched "The Apprentice", a television show starring Donald Trump, 0 otherwise

-   homealone2: 1 if the repsondent reports having watched "Home Alone 2", a movie featuring a cameo from Donald Trump, 0 otherwise
