---
title: "Code Glossary Prompt"
output: 
  github_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instructions

You will use the code glossary template for this assignment. The completed code glossary will be worth 10% of your final grade and will be due before the final week of class.

In each of the sections below, I've given you some prompts for definitions/examples/explanations of concepts and functions you should fill in.

For many examples, you'll need to use some data. You are free to use any data you like. There are many free and read-to-access datasets in R. Check them out here: https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/00Index.html

You can also feel free to use any data that we've used in the class.

Under each section header, there are some prompts alerting you to what you need to add. You are allowed to work with study groups to complete the code glossary, but **all work should be your own.** Definitions and explanations should be in your own words. If I see that students have used identical text, or have copied text from online, this will count as an **academic integrity violation that I will have to report.** The result will be an automatic failing grade. ***So don't cheat!***

## Getting Started

This section is all about how to start a project in RStudio and use .Rmd or RMarkdown files. Each subsection addresses the what, where, how, and why of working in RStudio and .Rmd files. For each question:

- **What**: Describe what the "thing" is. E.g., what is an R project?
- **Where**: Where do you find the "thing?" E.g., where do you click to start a new project?
- **How**: Walk through the steps to do the "thing." E.g., how do you create an R project?
- **Why**: Why would you want to do this? E.g., why would you want to create an R project?

Here's the code. You can copy and paste stuff over to your template file.


\#\#\# How to start a new project

What:

Where:

How:

Why:


\#\#\# How to use a .Rmd file

What:

Where:

How:

Why:


\#\#\# Save your work

What:

Where:

How:

Why:

\#\#\# How to install and attach packages

What:

Where:

How:

Why:

\#\#\# How to read in data

What:

Where:

How:

Why:


## Making a Plot

All plots should be produced using `{ggplot2}`. For each, you'll add the following:

- **Definition**: Define the kind of plot.
- **Code example**: Write some code that provides a sensible example of how to create the kind of plot.
- **Explanation**: In your own words, explain what the plot is supposed to show and when it would be appropriate to use.

You can copy and paste the below over to your template to get started:



\#\#\# A Histogram

Definition: 

Code example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation: 

\#\#\# A Box Plot

Definition: 

Code example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation: 

\#\#\# A Scatter Plot

Definition: 

Code example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation: 

\#\#\# A Line Plot

Definition: 

Code example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation: 

\#\#\# A Column/Bar Plot

Definition: 

Code example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation: 

## Show the Right Numbers

It's very easy to accidentally show the wrong numbers in your graphs, or to apply the wrong geom layer for your data. Knowing how to group your data, use small multiples, and do the right thing with frequency plots is essential.

\#\#\# Grouping

Definition: 

Code example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation: 

\#\#\# Faceting

Definition: 

Code example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation: 

\#\#\# Frequency Plots

Definition: 

Code example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation: 

\#\#\# Histogram with Fill Mapping

Definition: 

Code example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation: 

\#\#\# Density Plot with Fill Mapping

Definition: 

Code example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation: 

## Draw Maps

When we draw maps, not only do we need to make sure we use the correct geom in ggplot, but we also need to join the data we want to show with the coordinates necessary to draw geographic boundaries. That usually means that we need to *crosswalk* at least a couple of different datasets with each other and then use a `*_join()` function.

In the below, you'll first provide an example of how to join two datasets together. Then you'll show how to draw a map that shows the spatial distribution of some variable.

\#\#\# Join datasets together

Functions: left_join(), right_join(), full_join(), inner_join()

Definition:

Example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

\#\#\# Make a Map

Definition:

Example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:


## Tables, Labels, and Notes

### Preparing Data

Sometimes we need to get our data into a different format to plot it. That's where our tools from `{dplyr}` come in handy. In each subsection below you'll provide:

- **Definition**: Define the function.
- **Code example**: Write some code that provides a sensible example of how to use it.
- **Explanation**: In your own words, explain what the function does and when you would want to use it.

You can copy and paste the below over to your template to get started:

\#\#\# select()

Definition:

Example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

\#\#\# filter()

Definition:

Example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

\#\#\# mutate()

Definition:

Example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

\#\#\# summarize()

Definition:

Example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

\#\#\# group_by() + mutate() 

Definition:

Example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

\#\#\# group_by() + summarize() 

Definition:

Example:
    
&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;
    
Explanation:


### Labels and Notes

Adding labels and notes to your data viz can go a long way in helping your audience to identify patterns in data. We can add labels using a variety of functions. Provide an example of each below:

\#\#\# {geomtextpath}

Definition: The {geomtextpath} package provides helpful tools for plotting text along lines.

Example with geom_textline() and geom_labelline():

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

Example with geom_textsmooth() and geom_labelsmooth():

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

Example with geom_textvline() and geom_labelvline():

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

\#\#\# geom_text()

Definition:

Example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

\#\#\# geom_label()

Definition:

Example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

\#\#\# annotate()

Definition:

Example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

## Refining Plots

\#\#\# Modifying the Theme

Definition:

Example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

\#\#\# Modify Plot Labels

Definition:

Example:

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:


## Dealing with Survey Data

Survey data requires some special tools to deal with. In particular, we usually need a **code book** and we need to be prepared to spend some time *recoding* variables for analysis.

\#\#\# Code Book

What:

Where:

How:

Why:

\#\#\# Recodes

Definition: We have several functions in R to help us recode variables to make them ready for analysis. Recoding just means that we are converting existing values of variables into different values. Often, these new values are just more understandable and intuitive versions of the previous values. 

When we recode, we often will use the mutate() function in conjunction with the following functions:

Example with ifelse():

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

Example with socsci::frcode():

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

\#\#\# Summarizing Survey Responses

The {socsci} package provides helpful functions for summarizing survey data. These functions work seamlessly within the {dplyr} workflow.

Example with mean_ci():

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

Example with mean_ci() + group_by():

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

Example with ct():

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

Example with ct() + group_by():

&grave;&grave;&grave;{r}
    
&grave;&grave;&grave;

Explanation:

