---
title: "GC7"
author: "Miles D. Williams"
date: "2023-11-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      message = F,
                      warning = F,
                      dpi = 500,
                      out.width = "80%")

## packages
library(tidyverse)
library(coolorrr)
library(socsci)
library(googlesheets4)

## custom data viz
set_theme()   # you can get rid of this if you don't like it
set_palette(
  qualitative = c("steelblue", "gray20", "red3", "purple4", "forestgreen"),
  from_coolors = F
)

## survey data
gs4_deauth()
o23 <- range_read(
  "https://docs.google.com/spreadsheets/d/19Et52eKP1Yte9tainpfB7f_9sCB8UAVM36DbR2ySyaI/edit#gid=1526346509"
)

## link to the code book:
# https://drive.google.com/file/d/13HQ7HgKD4JS6CMYGUIUwgUykGqXttSV9/view?usp=sharing

## Some  Gifted Recodes 
o23 |>
  
    # make all column names lowercase
  rename_with(tolower, everything()) |>
    
    # start the recodes
  mutate(
    
    # race
    white = replace_na(q57_1, 0),
    hispanic = replace_na(q57_2, 0),
    black = replace_na(q57_3, 0),
    asian = replace_na(q57_4, 0),
    other = replace_na(q57_5, 0),
    race = case_when(
      white==1 & (black!=1 & hispanic!=1 & asian!=1 & other!=1) ~ "White",
      black==1 ~ "Black",
      asian==1 & (black!=1 & hispanic!=1) ~ "Asian",
      hispanic==1 ~ "Hispanic",
      other==1 & (black!=1 & hispanic!=1 & asian!=1)~ "Other"
    ),
    
    # gender
    gender = frcode(
      q53 == 1 ~ "Men",
      q53 == 2 ~ "Women"
    ),
    femtran = frcode(
      q54_1 == 1 ~ "Men",
      q54_2 == 1 ~ "Women",
      q54_3 == 1 | q54_1 == 1 ~ "Trans/N-B"
    ),
    
    # group participation
    greek = replace_na(q44_6, 0),
    varsity = replace_na(q44_1, 0),
    across(
      starts_with("q44_"),
      ~ replace_na(.x, 0)
    )
  ) |>
  rowwise() |>
  mutate(
    num_groups = 
      sum(c_across(starts_with("q44_")), na.rm  = T)
  ) |>
  ungroup() |>
  mutate(
    
    # partisanship
    pid7 = frcode(
      q3 == 1 ~ "Strong Democrat",
      q3 == 2 ~ "Democrat",
      q3 == 3 ~ "Lean Democrat",
      q3 == 4 ~ "Independent",
      q3 == 5 ~ "Lean Republican",
      q3 == 6 ~ "Republican",
      q3 == 7 ~ "Strong Republican"
    ),
    pid3 = frcode(
      q3 %in% 1:3 ~ "Democrat",
      q3 == 4 ~ "Independent",
      q3 %in% 5:7 ~ "Republican"
    ),
    
    # polarization
    polarized = abs(q11_6 - q11_8),
    
    # feeling thermometer questions
    donald_trump = q11_1,
    joe_biden = q11_3,
    denison_democrats = q11_6,
    adam_weinberg = q11_7,
    denison_com._service = q11_19,
    greek_life = q11_20,
    alex_pan = q11_33,
    wokeness = q11_30,
    denison_admin. = q11_22,
    mindfullness = q11_32,
    the_sunnies = q11_31,
    college_republicans = q11_8,
    student_government = q11_15,
    denison_forward = q11_27,
    onetwentyseven.blog = q11_16
  ) |>
  
    # importance of foreign policy issues
  mutate(
    across(q8_1:q8_12, ~ replace_na(.x, 0))
  ) |>
  rename(
    cyber_security = q8_1,
    ethnic_conflict = q8_2,
    climate_change = q8_3,
    human_rights = q8_4,
    migration = q8_5,
    terrorism = q8_6,
    trade = q8_7,
    regional_disintigration = q8_8,
    russian_aggression = q8_9,
    rising_china = q8_10,
    domestic_political_instability = q8_11,
    weapons_of_mass_destruction = q8_12,
    other_fp_concerns = q8_13
  ) |>
  
    # biden's foreign policy performance
  mutate(
    biden_fp = frcode(
      q10_1 == 5 ~ "Very poorly",
      q10_1 == 4 ~ "Poorly",
      q10_1 == 3 ~ "Neither",
      q10_1 == 2 ~ "Well",
      q10_1 == 1 ~ "Very well"
    )
  ) -> o23

```

Okay, for GC7, let's look at feelings toward a bunch of different figures and campus organizations. 

```{r fig.height=6, fig.width=8}

## organize the data to give me percentages by FT ranges:
o23 |>
  pivot_longer(donald_trump:onetwentyseven.blog) |>
  mutate(
    value_qt = cut(
      value,
      breaks = c(0, 25, 50, 75, 100),
      labels = c("0-25", 
                 "25-50",
                 "50-75",
                 "75-100"),
      include.lowest = T,
      ordered_result = T
    )
  ) |>
  group_by(name) |>
  ct(value_qt, show_na = F, cum = T) |>
  mutate(
    pct_label = ifelse(
      pct <= 0.1,
      " ",
      scales::percent(pct)
    ),
    name = str_replace_all(name, "_", " ") |>
      str_to_title()
  ) -> plt_dt

## now give me the averages for each FT
o23 |>
  pivot_longer(
    donald_trump:onetwentyseven.blog
  ) |>
  group_by(name) |>
  mean_ci(value) |>
  mutate(
    name = str_replace_all(name, "_", " ") |>
      str_to_title(),
    mean_label = format(mean, digits = 3)
  ) -> mean_dt

## merge in
plt_dt <- plt_dt |>
  left_join(mean_dt, by = "name")

## now it's time to build the figure
set_palette(
  qualitative = c("steelblue", "gray20", "red3", "purple4", "forestgreen"),
  diverging = c("red3", "white", "steelblue"),
  from_coolors = F
)
ggplot(plt_dt) +
  aes(
    x = pct,
    y = reorder(name, mean),
    fill = value_qt
  ) +
  geom_col(
    position = position_fill(reverse = T)
  ) +
  geom_text(
    aes(x = cum_pct,
        y = name,
        label = pct_label),
    color = "white",
    hjust = 1
  ) +
  geom_vline(
    xintercept = 1.1,
    linewidth = 20,
    color = "gray"
  ) +
  shadowtext::geom_shadowtext(
    aes(x = 1.1,
        y = name,
        label = mean_label,
        color = mean),
    show.legend = F,
    fontface = "bold"
  ) +
  ggpal(aes = "fill") +
  ggpal(type = "diverging", midpoint = 50) +
  labs(
    x = "Share of Students",
    y = NULL,
    title = "Feeling Thermometer Responses from\nDenison Students Regarding...",
    fill = "FT Ranges:\n"
  ) +
  scale_x_continuous(
    breaks = c(0, .25, .5, .75, 1, 1.1),
    labels = c(
      scales::percent(c(0, .25, .5, .75, 1)),
      "Mean\nResponse"
    )
  )
```

