---
title: "MA2"
format: pdf
editor: visual
---

## 

In this unit we've talked about many different theories of international politics. For MA2, you're objective is to select a theory that we discussed and argue why it is best for explaining Russia's invasion of Ukraine and the West's response. To make your case you'll write a brief five paragraph essay that follows the below format:

-   Paragraph 1: Begin the paragraph will a clear thesis statement, and include a brief summary of the points of evidence you will bring to bear to support this thesis.

-   Paragraphs 2-4: Each paragraph will introduce a point of evidence and explain why it supports your thesis. You can draw from news stories about events in Ukraine or arguments made by scholars about the war. Anything you cite, use in-text hyperlinks to the source.

-   Paragraph 5: Conclude by summarizing your argument and offer a quick prediction based on your chosen theory for how the war in Ukraine will come to an end.

Submit your essay to Canvas by Friday Nov. 8 by midnight.
