---
title: "Main Assignment 3"
subtitle: "Due 12.17 by 11:00am"
format: pdf
editor: visual
---

## Overview

Trying to replicate another researcher's analysis is what good science is all about. If an analysis only supports certain conclusions when a certain researcher does the work, or when you use a particular dataset, that's a problem. But if anyone can follow a researcher's analysis plan and come to the same conclusion using the same or different data, that lends extra credence to their findings.

**In this assignment you will work in teams of 2-3 and play the role of re-analyst for the work Bear Braumoeller did for his book *Only the Dead*.**

I've created [an online application](https://milesdwilliams15.shinyapps.io/trends-in-war/) that you will use to perform your analysis (but if you're extra ambitious or have some quantitative skills, you're welcome to the raw data to analyze it yourself). The app will produce data visualizations that resemble those Braumoeller produced when analyzing the incidence and size of international wars, and the role of international order in explaining patterns in international conflict.

The main kicker in this assignment is that you won't try to replicate Braumoeller's findings with the dataset he used. Instead, your analysis will be supported by a new dataset that has only been published in the past few years. It's called the [Militarized Interstate Events Dataset](https://internationalconflict.ua.edu/data-download/), and it contains corrections for the Militarized Interstate Disputes Dataset Braumoeller used in his research. It also is more granular. It offers event-level detail about militarized conflicts between countries. That means, beyond tracking whether a dispute took place between countries, it also documents each and every event that was part of a conflict. Does this more fine grained data support Braumoeller's conclusions? It's your job to find out in this MA.

With the results, you'll write a report that summarizes what you found. Your analysis will focus on replicating three key findings of Braumoeller's: (1) that rates of conflict over time don't support the decline of war thesis, (2) that sizes of conflicts over time don't support the decline of war thesis, and (3) that international order membership predicts who does and doesn't fight each other (e.g., that orders reduce conflict among members but increase conflict between orders or with countries outside the order).

## Submission Outline

Your final submission will be in the form of a paper that adheres to the following outline (Each criterion is worth an equal point toward your final grade):

-   **Top of the first page**

    -   Title

    -   Team member names

<!-- -->

-   **Introduction**:

    -   Include a section header.

    -   2 paragraphs.

    -   1st paragraph: Introduce your research question. You should mention the three findings of Braumoeller's that you want to replicate.

    -   2nd paragraph: State why the research question matters. Why do we care whether war is disappearing and whether international order can explain variation in international conflict?

    -   Use clear writing, with minimal typos or grammatical/stylistic errors, and appropriate transitions.

-   **Data and Design**:

    -   Include a section header.

    -   3 paragraphs.

    -   Briefly talk about the methods and data that Braumoeller uses in his book, and introduce the Militarized Interstate Events Dataset and how you'll use it to see if you can replicate Braumoeller's findings. You can read more about the MIE dataset, and why it is supposedly better, here: [The Militarized Interstate Events (MIE) dataset, 1816-2014](https://journals.sagepub.com/doi/10.1177/07388942231182674).

    -   You should not cite me or the app I've made for you as you discuss the data. Instead, cite the MIE dataset article in the previous link, and for any other measures used in your analysis, use the relevant citations for those as well. There will be a "Metadata" tab in the app that will tell you where each variable in the data comes from.

    -   Avoid listing out variables with bullet points. Just talk about the variables you'll use in plain English and in broad brushstrokes.

    -   Use clear writing, with minimal typos or grammatical/stylistic errors, and appropriate transitions.

-   **Analysis**:

    -   Include a section header.

    -   There should be no sub-section headers.

    -   3-6 paragraphs.

    -   Using the Trends in War app, put together data visualizations that summarize (1) trends in the rate of conflict, (2) trends in the size of conflict, and (3) trends in the rate of conflict between countries within, across, and outside of international orders.

    -   You must have at leas one visualization for each trend, but you are free to include more (no more than 6 total). You may want to consider what happens when you adjust or don't adjust for opportunities for conflict or normalize conflict size by population, for example.

    -   For each of your visualizations, make sure that you include your summary of each in a paragraph *before* the visualization.

    -   Also make sure that the very first sentence of each paragraph is a clear statement about what you found in the data.

    -   The remainder of the paragraph should be dedicated to helping your audience interpret the figure.

    -   Use clear writing, with minimal typos or grammatical/stylistic errors, and appropriate transitions.

-   **Conclusion**:

    -   Include a section header.

    -   2 paragraphs.

    -   Briefly summarize your findings.

    -   Discuss the big-picture implications of what you found.

-   **Citations:**

    -   You may use any citation style you wish, as long as you use it consistently.
