---
output: 
  stevetemplates::beamer:
    keep_tex: TRUE
    latex_engine: pdflatex # use xelatex here instead! I recommend it, but this is minimal reprex
    dev: cairo_pdf # I typically comment this out  if latex_engine: pdflatex
    slide_level: 3 # I prefer this, but I won't force it on you.
title: 'Sovereinty and "Society"'
subtitle: "DPR 190: War, Wealth, & World Politics"
author: Miles Williams
institute: Data for Political Research
# titlegraphic: "`r paste0(Sys.getenv('HOME'), '/Dropbox/clemson/watermarks/clemson-university-wordmark-orange-purple.png')`"
# scaletg: .9 # Optional, proportional (0, 1) to paper width. Defaults to .3
fontsize: 12pt
make149: TRUE
# mainfont: "Open Sans" # Try out some font options if xelatex
# titlefont: "Titillium Web" # Try out some font options if xelatex
# specify color as six-digit RGB (no pound sign)
# primarycolor: "990000" 
# secondarycolor: "000099"
---

```{r setup, include=FALSE, cache=F, message=F, warning=F, results="hide"}
knitr::opts_chunk$set(cache=F)
knitr::opts_chunk$set(fig.path='figs/')
knitr::opts_chunk$set(cache.path='cache/')
knitr::opts_chunk$set(echo = F)

knitr::opts_chunk$set(
                  fig.process = function(x) {
                      x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
                      if (file.rename(x, x2)) x2 else x
                      }
                  )
library(tidyverse)
library(stevemisc)
```


# Sovereignty

### Sovereignty

### What is it?


### What is it?

1. Countries should accept the borders of other countries and not use force in an attempt to change them.

2. Countries should not interfere with events inside other countries.

3. Governments should have a free hand to do as they please in their own borders.

# Anarchical Society

### Anarchical Society

### What is it?


### What is it?

1. The "citizens" of this society are ***countries***.

2. Governments and leaders of these countries are free to act as they wish within their own borders.

3. The members of this society respect and accept this freedom of action on the part of others.

### Who gets to be part of the society?


### Who gets to be part of the society?

Sovereignty is two parts:

1. Self-determination

2. Acceptance by others

### How is this society maintained?


### How is this society maintained?

1. Balance of power

2. Deterrence

# Next time

### Next time

Stephen Krasner, "Who Gets a State and Why?"

Katy Collin, "The Referendum in Catalonia Explained"