---
output: 
  stevetemplates::beamer:
    keep_tex: TRUE
    latex_engine: pdflatex # use xelatex here instead! I recommend it, but this is minimal reprex
    dev: cairo_pdf # I typically comment this out  if latex_engine: pdflatex
    slide_level: 3 # I prefer this, but I won't force it on you.
title: An Example R Markdown Document
subtitle: (A Subtitle Would Go Here if This Were a Class)
author: Steven V. Miller
institute: Department of Economic History and International Relations
# titlegraphic: "`r paste0(Sys.getenv('HOME'), '/Dropbox/stockholm/su-logotyp.png')`"
# scaletg: .9 # Optional, proportional (0, 1) to paper width. Defaults to .3
# titlegraphshift: "\\vspace{6cm}" # Optional, you can delete this if you want.
fontsize: 10pt
make149: TRUE
# mainfont: "Open Sans Light" # Try out some font options if xelatex
# titlefont: "Titillium Web" # Try out some font options if xelatex
# specify color as six-digit RGB (no pound sign)
# primarycolor: "990000" 
# secondarycolor: "000099"
---

```{r setup, include=FALSE, cache=F, message=F, warning=F, results="hide"}
knitr::opts_chunk$set(cache=TRUE)
knitr::opts_chunk$set(fig.path='figs/')
knitr::opts_chunk$set(cache.path='cache/')

knitr::opts_chunk$set(
                  fig.process = function(x) {
                      x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
                      if (file.rename(x, x2)) x2 else x
                      }
                  )
library(tidyverse)
library(stevemisc)
library(peacesciencer)
load(here::here("DPR 190", "Data", "ISreplicationdataset.Rdata"))
dt <- x; rm(x)
library(mgcv)
library(gratia)
library(sjPlot)
```

```{r}
glm(
  def_eff ~ us_SH1995 + us_EH1995 +
    log(pop) + mid2 + log(rgdp) +
    polity2 + country,
  data = dt |> mutate(country = as.factor(country)),
  family = quasipoisson
) -> model_fit
```

```{r}
plot_model(
  model_fit,
  type = "eff",
  term = c("us_SH1995")
) +
  labs(
    x = "U.S. Security Hierarchy",
    y = "Expected Military Spending per GDP",
    title = "Model Predictions"
  )
```


```{r}
plot_model(
  model_fit,
  type = "eff",
  term = c("us_EH1995")
) +
  labs(
    x = "U.S. Economic Hierarchy",
    y = "Expected Military Spending per GDP",
    title = "Model Predictions"
  )
```

